# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
rvm:
- 2.1.2
install:
- ./Util/install.sh
script:
- ./Util/build.sh

notifications:
  email: false
